package com.notyourd3.bar.core;

import com.google.common.eventbus.EventBus;
import com.jackiecrazi.bar.Tags;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class BARModContainer extends DummyModContainer {
    public BARModContainer() {
        super(new ModMetadata());
        ModMetadata meta = getMetadata();
        meta.autogenerated = true;
        meta.modId = "betterarcherycore";
        meta.name = "Better Archery Core";
        meta.version = Tags.VERSION;
        meta.authorList = Arrays.asList("notyourd3");
        meta.parent = "BetterArcheryReborn";
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

}
